=== vanvliet-leiden/dmt-20192020/Vliet/attributes.dtd
<!ELEMENT title (#PCDATA)>
<!ATTLIST title type  ( painting | novel | poem | ballet | play ) #REQUIRED>
<!ELEMENT attributes (#PCDATA | p)*>
<!ELEMENT p (title)*>
<!ELEMENT genre (#PCDATA)>
<!ATTLIST genre type (modernism | post-modernism) #REQUIRED >

=== vanvliet-leiden/dmt-20192020/Vliet/attributes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE attributes SYSTEM "attributes.dtd">
<attributes>
    <p> Modernism made an impact early in the 20th century century. Artists such as the Henri
        Matisse, the Norwegian Edvard Munch (whose 1893 <title>Scream</title> summed up modern urban
        alienation) and the Austrian Oskar Kokoschka used vivid colours and broad brushstrokes to
        express mood and emotion, and the personal feelings evoked by a situation rather than the
        way it literally looked. Much avant-garde modernist culture – books such as James Joyce's
        <title>Ulysses</title>, poems such as T. S. Eliot's <title>The Waste Land</title> and
        Ezra Pound's <title>Hugh Selwyn Mauberley</title>, modern art, modern architecture, ballets
        staged by Sergei Diaghilev – was, for most of the first half of the 20th century, only
        enjoyed by small groups of intellectuals. The public reacted with jeers and contempt to
        Stravinsky’s <title>The Rite of Spring</title>, and D.H. Lawrence's <title> Lady
            Chatterley's Lover</title> has been banned in the UK for several decades. Whereas
        Pirandello's <title>Six Characters in Search of an Author</title> and Ionesco's
        <title>Rhinoceros</title> shaped the face of modernism in the theatre, their first
        stagings attracted extremely hostile public reactions. </p>
</attributes>
